### ISSUE TITLE
RavenDB cluster - docker

### ISSUE THREAD

**Issue by njunior1980** [DavidBoike/feedback#6]
Hi, congrats by article. I tried but hadn't success. My cluster is created, but I can't to connect by Ravendb client. Can you help me? Thanks David.

"hostos:172.24.83.193" is my public ip (my computer/router).

https://www.davidboike.dev/2019/06/creating-a-ravendb-cluster-in-docker/

```
version: '3'
services:
  raven1:
    container_name: raven1
    image: ravendb/ravendb:5.1.6-ubuntu.20.04-x64
    ports:
      - 8080:8080
      - 38888:38888
    extra_hosts:
      - "hostos:172.24.83.193"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://0.0.0.0:8080"
      - "RAVEN_PublicServerUrl=http://hostos:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
      - "RAVEN_PublicServerUrl_Tcp=tcp://hostos:38888"
```
![image](https://user-images.githubusercontent.com/5822802/115634568-c4fad600-a301-11eb-98df-f5c509a7f6ff.png)

![image](https://user-images.githubusercontent.com/5822802/115634411-7ea57700-a301-11eb-8c97-bfef32f606b8.png)
